### ISSUE TITLE
question: is this based on the old libretro source?

### ISSUE THREAD

**Issue by fr500** [libretro/libretro-fba#1]
Is this based on the old libretro source with updated FBA sources
Or is it a brand new port?

BTW, if you have time, I think this core doesn't implement the SRAM interface, so saves end up littering the ROM folder or the working dir.

Could you add a sane location for saves by using RETRO_ENVIRONMENT_GET_SAVE_DIRECTORY?

**Comment by barbudreadmon** [comment]
I used fba stand-alone as a start, and since i haven't written C/C++ that much since i learned it (20 years ago), i used old libretro port a lot to help me.
