### ISSUE TITLE
Colors off in Konami games (rpi2)

### ISSUE THREAD

**Issue by ochief** [libretro/libretro-fba#10]
I believe you have a RPI, can you please try some Konami games and see if the colors look correct?  

I have been testing this via the latest Lakka nightly so it is possible that is the cause, but the color palette for Konami games only seem to be Blue and Yellow.

Initially I thought it was only happening to recently added games I.E. ''88 Games' and 'Wild West C.O.W.-Boys of Moo Mesa' but it is also happening with 'Sunset Riders' which I know has previously worked using an older version of FBA.

**Comment by Oggom** [comment]
Most likely the as https://github.com/libretro/libretro-fba/issues/7

**Comment by barbudreadmon** [comment]
Most konami games have this issue, i thought the same issue applied to old repo but if you say it didn't, i'll check the differences.

**Comment by ochief** [comment]
Sorry Oggom you're right, I should have noticed this was the same issue.  Barburdreadmon, you might as well close this as a duplicate.  Thanks for looking into it.

**Comment by barbudreadmon** [comment]
Right now i'm mainly searching for a way to run games from Irem M72, M92 and M107 boards, but i'll give a look at konami games after i have found out the issue/solution about Irem.

**Comment by barbudreadmon** [comment]
Fixed
