### ISSUE TITLE
About a fix konami games colours

### ISSUE THREAD

**Issue by saitoh00** [libretro/libretro-fba#15]
In version 35 there was this bug, I have seen that in the last 36 version also exists, however, the Pc version dont have this bug (I'm using Rpi 2).

Any solution? The color is everything in Konami games I hope you can identify and fix the problem of colors.

Greetings

**Comment by barbudreadmon** [comment]
By pc version you mean fba standalone on windows ? I already tried to fix that bug, i talked about it with fba standalone devs ( see http://neosource.1emulation.com/forums/index.php?topic=2693.30 ), we didn't find a fix.

**Comment by saitoh00** [comment]
When i say pc version i mean http://www.fbalpha.com/downloads/

**Comment by barbudreadmon** [comment]
Both use the same drivers sources. The only difference is the frontend part.

**Comment by saitoh00** [comment]
La verdad, apenas llevo unos meses empezando con linux y con el tema de raspberry pi.. y no entiendo como siendo las mismas fuentes que es lo que cambia para que en esos juegos en concreto cambie la paleta de colores tanto, el resto de roms de este emulador funciona a la perfección, tanto a nivel de emulación como de rendimiento.

Tengo muchísimo interés en que se encontrase una solución,ya que creo que es el emulador arcade para raspberry más actualizado y si es necesario hacer pruebas o ayudar en lo que sea, tengo disponible una tarjeta de memoria para tales fines, así que si se te ocurre lo que sea y necesitas un betatester...cuenta conmigo.

**Comment by saitoh00** [comment]
I see afba for android, its vers. 35 and the konami games have colour fix. There is the github: https://github.com/Cpasjuste

**Comment by barbudreadmon** [comment]
Seems like i finally found out the issue, check last commit.
