### ISSUE TITLE
Problems with any game on rpi2 

### ISSUE THREAD

**Issue by Speedvicio** [libretro/libretro-fba#19]
Some Irem hardware-based games don't work.
Framerate issues and crackly audio on Konami and Sega 90' hardware-based games (for example Vendetta, Moonwalker, Outrun, Golden Axe, Asterix And Obelix , Teenage mutant ninja turtles).
Polygame Master Game don't work (I have already put the correct bios on the rom folder).

**Comment by barbudreadmon** [comment]
What's your fba-libretro version and your rpi2 distro ? I don't have most of those issues.

**Comment by Speedvicio** [comment]
It's the last build from lakka nightly.
http://sources.lakka.tv/nightly/RPi2.arm/

**Comment by barbudreadmon** [comment]
I don't use lakka, i don't plan to install it to check which version/repo of libretro-fba it uses, and i don't plan to search for the answer on google, so give me a straight answer : which libretro-fba version it uses ? You just have to go to retroarch menu and read the bottom of the screen, it should be kinda easy.

**Comment by Kivutar** [comment]
Hi @barbudreadmon , it uses the latest master 0093227f57ec5045daa309eaeba007366460181a of this repo

**Comment by barbudreadmon** [comment]
No polygame Master Game will work ?
About framerate issues and crackly audio on Konami/Sega 90s games, is it full time or only at some time ?
What's your overclocking settings ?

**Comment by barbudreadmon** [comment]
Ok, i gave a few tests on my RPI2 :
=> Every PGM games i tried (kov, kov2, ddp2, puzzli2, ...) ran flawlessly. I can't find a single PGM game not working so your romset is probably the wrong one, perhaps you are not even using this core but the old core from the old repo, you wouldn't be the first one...
=> The few Konami/Sega 90s games i tried (from your list of buggy games) ran flawlessly, sure the audio is bad, the SPU was a Z80, but i wouldn't call it "crackly", it is the same quality, perhaps a little better, you could hear on any megadrive game. No framerate issue either, at least for the first few minutes, i didn't go deep in those games. Just my guess but i tried lakka once (around a year ago on my RPI1), performances were poor compared to retropie, and i'm not even using retropie anymore (i'm using a homemade gentoo based setup), mainly because of performances.
=> About IREM games, there was already an issue filled and i have been trying to fix it with help from upstream for some months now.

**Comment by Speedvicio** [comment]
I tested Demon Front pgm game, the fba module crash at start and reboot lakka GUI (I am using a romset aligned with the latest available  version of mame and compatible with the official final burn alpha).
The problem of bad audio is a consequence of the low frame rate of Konami titles , I tested all the games based on the particular Konami hardware and the only one that runs smoothly is the Simpson game.
I state that I tested the games without overclocking and overclocking rpi2 with the same results.
The same problem also occurs with Taito 90' hardware games (liquid kid, etc)  with some Sega games (Out Run, Moonwalker, S. Hang On, etc) and with any 90' Data East hardware based game.
Everything else runs perfectly , for example Psyko  harwdware based games which in theory should also be more resource-hungry hardware.
Sorry for the bad english.

**Comment by barbudreadmon** [comment]
Demon Front running fine here. People should seriously stop thinking "Vanilla MAME roms work with FBA". 

First thing, current FBA is based on MAME 162 romset, which is not the latest MAME set.

Second thing, FBA v0.2.97.36 use MAME 162 romset as the main rom file provider, but the way they are divided and packed into zip files is different, and sometimes there are files added from other sources, the dmnfrnt.zip from MAME 162 romset contains more files than the dmnfrnt.zip from FBA v0.2.97.36, the pgm.zip from MAME 162 romset contains less file than the pgm.zip from FBA v0.2.97.36, you need ddp3_bios.u37 and bios.u42 (with the right crc) in either dmnfrnt.zip or pgm.zip for Demon Front to run on latest FBA, both those files are missing in dmnfrnt.zip/pgm.zip from MAME 162 romset.

If you want to play with FBA, build a FBA romset !

Again, i don't experience those framerate issues with any of those 90's games, and i'm not sure running Psyko based games fine means a lot. All depends on how things are coded, and i heard from FBA developper that some old systems (like konami) are quite tricky to emulate.

**Comment by barbudreadmon** [comment]
So you were able to run pgm games after rebuilding the romset ?

About your issue with Z80 based games, i'll try porting drz80 (a z80 cpu emulator optimized for arm32) to libretro-fba when i'll have some free time, but don't expect much (i tried the same with cyclone, a 68k cpu emulator optimized for arm, without success).

**Comment by Speedvicio** [comment]
Problems occur in the arm versions (at least on lakka), I also tested the version for i386 on an eeepc 4g with 600 mhz cpu, and the problem does not occur, and start even those games that do not start on rpi2 for example raiden or r -type leo.
Apparently libretro-fba ported to i386 it is better optimized.
As for the pgm games ,on lakka you were right, the bios that I had in my home PC was full with two binary files are missing, however, the set "as incompatible as you say", the in official fba PC version will be still be able to run games without problems.
For the moment, if I want to play those games continue to use fba or mame on desktop computer.

**Comment by barbudreadmon** [comment]
Well, it's a fact fba was written for i386, you can't expect 100% compatibility/speed on another architecture, especially when the computing power is lower.
I'm closing since the only real issue remaining is the irem games (which is a duplicate) :
https://github.com/libretro/libretro-fba/issues/9
