### ISSUE TITLE
Universe Bios not saving settings (both FBA core and FBA Neogeo core)

### ISSUE THREAD

**Issue by Warriors-Blade** [libretro/libretro-fba#20]
Just tested in the latest FBA cores in RA and they simply will not save your Uni Bios settings , it always defaults on start up of a neogeo game.

Any ideas on this matter?

**Comment by barbudreadmon** [comment]
By Uni Bios settings, you mean the fact that it starts on unibios ? or the settings you select in unibios for a specific game ?

**Comment by Warriors-Blade** [comment]
Sorry for the late reply,  the universe bios will default each time its ran, once its turned on in the FBA core it stays on for all neogeo games it just will not save your settings like it does in actual FBA but in FBA its a per game basis, you must turn it on for each game but it will still save your uni bios settings on exit.

**Comment by fr500** [comment]
https://github.com/libretro/libretro-fba/pull/31

**Comment by Warriors-Blade** [comment]
Thanks a ton for fixing this issue fr5000.
