### ISSUE TITLE
unable to build on raspberry pi2 +

### ISSUE THREAD

**Issue by nolageek** [libretro/libretro-fba#21]
last part of the build where the error is:

g++ -O3 -DNDEBUG -fPIC -Wno-write-strings -DUSE_SPEEDHACKS -D__LIBRETRO__ -D__LIBRETRO_OPTIMIZATIONS__ -DWANT_NEOGEOCD -DLSB_FIRST -marm -mcpu=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard -DINLINE="static inline" -DSH2_INLINE="static inline" -D__LIBRETRO_OPTIMIZATIONS__  -DPROFILE_PERFORMANCE -std=gnu++0x -DFRONTEND_SUPPORTS_RGB565 -Isrc/burner/win32 -Isrc/burner/libretro -Isrc/burner/libretro/tchar -Isrc/burn -Isrc/cpu -Isrc/burn/snd -Isrc/burn/devices -Isrc/intf -Isrc/intf/input -Isrc/intf/cd -Isrc/burner -Isrc/cpu -Isrc/cpu/i8039 -Isrc/dep/libs/zlib -Isrc/burn/drv/capcom -Isrc/burn/drv/konami -Isrc/burn/drv/dataeast -Isrc/burn/drv/cave -Isrc/burn/drv/neogeo -Isrc/burn/drv/psikyo -Isrc/burn/drv/sega -Isrc/burn/drv/toaplan -Isrc/burn/drv/taito -Isrc/dep/generated -Isrc/dep/libs -c src/burn/drv/midway/d_kinst.cpp -o src/burn/drv/midway/d_kinst.o
/usr/lib/gcc/arm-linux-gnueabihf/4.7/cc1plus: relocation error: /usr/lib/gcc/arm-linux-gnueabihf/4.7/cc1plus: symbol efPv, version GLIBC_2.4 not defined in file libc.so.6 with link time reference
makefile.libretro:571: recipe for target 'src/burn/drv/midway/d_kinst.o' failed
make: *** [src/burn/drv/midway/d_kinst.o] Error 1

**Comment by nolageek** [comment]
I changed the 5th line in makefile.libreto from 'NO_MIDWAY := 1' to 'NO_MIDWAY = 1'

now I'm getting this error:

 -DPROFILE_PERFORMANCE -std=gnu++0x -DFRONTEND_SUPPORTS_RGB565 -Isrc/burner/win32 -Isrc/burner/libretro -Isrc/burner/libretro/tchar -Isrc/burn -Isrc/cpu -Isrc/burn/snd -Isrc/burn/devices -Isrc/intf -Isrc/intf/input -Isrc/intf/cd -Isrc/burner -Isrc/cpu -Isrc/cpu/i8039 -Isrc/dep/libs/zlib -Isrc/burn/drv/capcom -Isrc/burn/drv/konami -Isrc/burn/drv/dataeast -Isrc/burn/drv/cave -Isrc/burn/drv/neogeo -Isrc/burn/drv/psikyo -Isrc/burn/drv/sega -Isrc/burn/drv/toaplan -Isrc/burn/drv/taito -Isrc/dep/generated -Isrc/dep/libs -c src/burn/drv/pst90s/d_1945kiii.cpp -o src/burn/drv/pst90s/d_1945kiii.o
src/burn/drv/pst90s/d_1945kiii.cpp: In function ‘INT32 DrvFrame()’:
src/burn/drv/pst90s/d_1945kiii.cpp:420:1: internal compiler error: in push_minipool_fix, at config/arm/arm.c:13055
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.7/README.Bugs> for instructions.
Preprocessed source stored into /tmp/cc3VdqPt.out file, please attach this to your bugreport.
makefile.libretro:571: recipe for target 'src/burn/drv/pst90s/d_1945kiii.o' failed
make: *** [src/burn/drv/pst90s/d_1945kiii.o] Error 1

**Comment by barbudreadmon** [comment]
relocation error, internal compiler error, ... are sometimes issues with your toolchain, sometimes with weared off hardware, sometimes with your spec, ...

A few thing you could try : 
- close any running program on your rpi2
- upgrade gcc/glibc/binutils (the so called "toolchain")
- change settings in /boot/config.txt
- try on a new sd card

From the default gcc used (4.7), i also assume you are using raspbian wheezy, which is kinda deprecated for rpi2, and is probably related to your issues, you should consider switching to jessie (if you really love debian), recalbox (i kinda prefer this one) or lakka (i don't really like this one).

**Comment by barbudreadmon** [comment]
No replies, i close

**Comment by joolswills** [comment]
builds fine on gcc 4.8 on Raspbian Wheezy also (newer gcc packages are provided by http://archive.raspberrypi.org/debian/ which is enabled by default.

**Comment by joolswills** [comment]
Raspbian Wheezy is not deprecated for rpi2 btw - it's still the recommended stable release and provided on raspberrypi downloads page. It also still gets packaged firmware/kernel updates

**Comment by barbudreadmon** [comment]
Well, i had a lot of issues with raspbian, ICE and such. All issues disappeared when i switched to another distro (Gentoo), and i also noticed a fps increase over raspbian. So yes it is the "recommended stable release", yes it is easy to install and to maintain, yes you easily find support for it, but i'm still 100% sure you get better results/less issues with other distro if you know what you are doing.

**Comment by joolswills** [comment]
Sure. I was just wanting to clarify with rpi2 and Wheezy vs Jessie, which is unrelated to whether other distros may suit people better or whether other distros are better than Raspbian.
