### ISSUE TITLE
PS3 controller issue on SELECT button

### ISSUE THREAD

**Issue by lollo78** [libretro/libretro-fba#22]
Hi, on my Raspberry Pi2 with OpenElec and Retroarch (launched with Advanced Launcher) I use the "fba_libretro.so" (display_version = "v0.2.97.36") extracted from Lakka for RPi2.

With MAME games, libretro-fba has an issue to manage PS3 controller that is not present in all the other libretro core used on my system (imame4all, picodrive, snes9x, genesis_plus_gx, pcsx_rearmed...). 

This is my working joypads configuration in retroarch.cfg:

input_player1_joypad_index = 0
input_player1_a_btn = 13
input_player1_b_btn = 14
input_player1_x_btn = 12
input_player1_y_btn = 15
input_player1_l_btn = 10
input_player1_r_btn = 11
input_player1_l2_btn = 8
input_player1_r2_btn = 9
input_player1_l3_btn = 1
input_player1_r3_btn = 2
input_player1_start_btn = 3
input_player1_select_btn = 0
input_player1_left_btn = 7
input_player1_up_btn = 4
input_player1_right_btn = 5
input_player1_down_btn = 6
input_player1_l_x_plus_axis = +0
input_player1_l_y_plus_axis = +1
input_player1_l_x_minus_axis = -0
input_player1_l_y_minus_axis = -1
input_player1_r_x_plus_axis = +2
input_player1_r_y_plus_axis = +3
input_player1_r_x_minus_axis = -2
input_player1_r_y_minus_axis = -3

input_player2_joypad_index = 1
input_player2_a_btn = 13
input_player2_b_btn = 14
input_player2_x_btn = 12
input_player2_y_btn = 15
input_player2_l_btn = 10
input_player2_r_btn = 11
input_player2_l2_btn = 8
input_player2_r2_btn = 9
input_player2_l3_btn = 1
input_player2_r3_btn = 2
input_player2_start_btn = 3
input_player2_select_btn = 0
input_player2_left_btn = 7
input_player2_up_btn = 4
input_player2_right_btn = 5
input_player2_down_btn = 6
input_player2_l_x_plus_axis = +0
input_player2_l_y_plus_axis = +1
input_player2_l_x_minus_axis = -0
input_player2_l_y_minus_axis = -1
input_player2_r_x_plus_axis = +2
input_player2_r_y_plus_axis = +3
input_player2_r_x_minus_axis = -2
input_player2_r_y_minus_axis = -3

input_enable_hotkey_btn = 0
input_exit_emulator_btn = 16
input_menu_toggle_btn = 3

With the last 3 options I can enter in Retroarch menu holding down the SELECT button and pressing START. To quit a game, and return in Kodi, I hold down SELECT and press PS button.

In FBA Libretro happens this (I notice that this happens with "new" games like Street Fighter II and not with old roms like Bubble Bubble):
On "Player 1 Controller" the SELECT button doesn't insert coin, but can enter in Retroarch menu and quit to Kodi. 
On Player 2 Controller", instead, SELECT insert coin, but not to quit to Kodi or enter in Retroarch menu.
So, to play alone I have to power on also the second controller.
Thx a lot for any help

**Comment by barbudreadmon** [comment]
No issue here with dualshock 3 + autoconfig. Menu toggle and enable hotkey are switched on my config, you should try that (Having select as both hotkey enabler and credit adder seems bad to me)

**Comment by lollo78** [comment]
Hi, switching to
input_enable_hotkey_btn = 16
input_exit_emulator_btn = 0
input_menu_toggle_btn = 3
fix the issue. And now the hotkeys works fine.
Thx a lot
