### ISSUE TITLE
Neogeo bios/region selection and Test menu missing from vanilla FBA

### ISSUE THREAD

**Issue by Warriors-Blade** [libretro/libretro-fba#25]
I just noticed that the Test menu and the region/neogeo bios selection is missing from the FBA core, could we please get those hooked into the core?

**Comment by nemo93** [comment]
hi there,

it works on my setup (Retropie last version + libretro-fba updated from source). You have to rely on Unibios for that. So turn it on in RA settings then quit and launch a game there you should see the Unibios screen. You have to press 3 buttons at the same time to enter. You could also go the RA settings/Core options and you could enabled (or disabled doesn't matter) the Diagnostics item when you hit Resume content the Test menu should appear. 

Edit: for some reason I can't use Unibios 3.1 (up to 3.0 only). I'm going to raise a ticket for that.

Hope this helps.

TS

**Comment by Warriors-Blade** [comment]
This has now been added , thanks a bunch guys.
