### ISSUE TITLE
Neogeocd - Shinsetsu Samurai Spirits - Bushidohretsuden (Japan) not working

### ISSUE THREAD

**Issue by thorias** [libretro/libretro-fba#256]
Hello,

I was testing a neogeo cd game: Shinsetsu Samurai Spirits - Bushidohretsuden (Japan) on a RPI 3B+, it loads fine until we reach the main menu and when we launch game start, it start to load and then a crash with the following error message occurs: "DISC I/O error ( id = 0002 ) please power off".
the same image (cue/bin) works fine with other emulators (Raine/Win10...when the game is launched it says: applique le hack de vitesse 7a0:Garou). Could you have a look into this? 
As it will bring another one as I'd like to play the same game but with the Fr patch, again the patched version works fine in Raine but in FBA it just plain crash (it's a cue/bin as well).

**Comment by barbudreadmon** [comment]
This repo is deprecated, use https://github.com/libretro/fbalpha, and make sure you are using the latest version built from sources.
