### ISSUE TITLE
[RPI2] Add support for Universe Bios 3.1 - not working - minor

### ISSUE THREAD

**Issue by nemo93** [libretro/libretro-fba#26]
Hello,

I still can't use UB 3.1 even if this specified commit (#24) says otherwise :( I'm running Retropie last version with a freshly build from source version of libretro-fba. I've double-checked the name of the bios file and it matches this: uni-bios_3_1.rom

I've tried removing all other uni-bios_xx.rom files from neogeo.zip but without any success.

Apart from that this core works perfectly with Neogeo games! #happy so thanks for that.

cheers,

TS

**Comment by barbudreadmon** [comment]
When you say "a freshly build from source version of libretro-fba", you mean through their retropie_setup script ? If that's the case, you use the old fba-libretro core, not this libretro core.

**Comment by Alcaro** [comment]
Added a comment to the fba-libretro description. Why do those old repos exist at all?

**Comment by Oggom** [comment]
The old repo is used for the Wii port afaik.

**Comment by nemo93** [comment]
thank you guys for having a look.

@barbudreadmon: yes you're right. I did that from the retropie_setup. Which is just useless given that I've just seen it's pointing to the "old" repo :( (fba-libretro, names are quite ... confusing). Silly me \o/

So I feel very ashamed :( I'm compiling by hands (with cc/g++ 4.8) this core right now and I'll give it a try later today. I'll update this thread of course. Sorry for that...
cheers,

TS

**Comment by nemo93** [comment]
Everything's cool after recompiling *this* repo. It's awesome as all my Neo Geo sound issues are gone :) I can play "newer" games \o/

Sorry again for this...
