### ISSUE TITLE
[RPI2] Few games status / issues

### ISSUE THREAD

**Issue by nemo93** [libretro/libretro-fba#27]
Hi there,

after playing for a while today on my Retropie install and after building the *right* version (!) I've ran a few games to see the difference with the FBA core shipped by default with Retropie. Well the difference is pretty much amazing :) 
EDIT: this core is now the default in Retropie \o/ https://github.com/RetroPie/RetroPie-Setup/commit/483093701c0d54fd04e853d4e6b2646d1059eb56

1. All Neo Geo sound issues are gone (KizunaE, MS3, etc). GONE!
2. Konami and Banpresto games do work flawlessly (Asterix yeah and Sailor Moon among others)
3. Capcom most recent games (cps3) just DO work. I just couldn't believe it! Jojo, SF 3rd Strike, etc do work full speed with sound. Perhaps few glitches here and there with Jojo and the sound sometimes is not crackling but let's say weird (3rd Strike selection screen for instance), lot of echo I'd say.
4. IGS/PGM games do work also. Amazingly. Including the fantastic Demon Front. As for the point above perhaps the sound is "weird" at random but it's all very playable and enjoyable.

Only for this list I'm glad to have switched to this FBA core! So big thanks guys. 

1. However none of the IREM games are working :( This is very sad news (In the Hunt (m92), Under Cover Cops (m92), R-Type 1 (m72), R-Type Leo (m92), Hammerin' Harry / Daiku no Gensan (M72 / M81 / M82 / M84), Gunforce 1&2 (m92), Hook (m92) and one of the best game ever made Ninja Baseball Bateman!! (m92)). I'm afraid there's nothing that could be done right? This may have been asked via #9 but not sure so this ticket... 
2. Also another issue is with the "light gun" games like Operation Wolf/Thunderbolt where I could see the cross-hairs but the actual line of fire doesn't follow it. Instead every time the trigger is pulled a shot is being made at the very center of the screen irrespective of the cross-hair location.
3. Darius / Darius 2 / Ninja Warriors runs slow I trust this is due to the hardware being emulated. It's still playable though.
4. Robocop 2 runs slow
5. Control issue with games like Midnight Resistance or Forgotten Worlds. Can't shoot in 8-way direction.
6. I'm also having an issue with Red Earth (CPS3). Game launches but after main menu I'm being asked to insert a CD!

It would be absolutely awesome to be able to run these games. If I can do anything please let me know. Thanks again for the work!

**Comment by barbudreadmon** [comment]
Only Irem m72, m92 and m107 boards don't work : even with help from upstream, i didn't figure out what's wrong, and i don't have that much time to work on this. Old repo got same issues.

**Comment by nemo93** [comment]
Hi @barbudreadmon,

thanks for answering. I'm out of luck as all IREM games I've mentioned do rely on those boards (from top of my head I need to double check but anyway these games don't play). Would you like me to close this ticket and create separate ones for the other issues? Or do you really have no time at all and it doesn't worth it?
cheers,

**Comment by nemo93** [comment]
FYI the IREM games are supported on Mame 0.78 (2003) core. They work perfect with sound etc except Ninja Baseball that suffers from slow downs (but still playable).

**Comment by barbudreadmon** [comment]
Ok, i'll give a look to mame 0.78 this week-end.

**Comment by nemo93** [comment]
cheers @barbudreadmon. FYI the "light gun" games like Operation Wolf/Thunderbolt also do work nicely with mame 0.78 and so play Darius / Darius 2 / Ninja Warriors, full speed. Robocop 2 runs also full speed on mame. However this mame version can't run cps2/3 games at all...

**Comment by twinaphex** [comment]
cps2 games work in MAME 0.78 but you need MAME 0.78 roms for the cps2 games.

**Comment by nemo93** [comment]
my bad @twinaphex you're absolutely right. After doing a quick search I've been able to find those encrypted roms. As such I do confirm all CPS2 games actually work perfectly on MAME 0.78 (aka mame2003). Yet I'm having hard time with Sega System16 as only few games work whereas with this FBA core it's perfect.

@barbudreadmon I'm also having an issue with Red Earth (CPS3). Game launches but after main menu I'm being asked to insert a CD!
