### ISSUE TITLE
[RPI2] Atomic Robo Kid

### ISSUE THREAD

**Issue by nemo93** [libretro/libretro-fba#29]
This game launches with no troubles, the ROMs  check screens appears and all is still going very ok. Yet after the this screen instead of having the game itself emulator sits in an option/service menu that I just can't exit. I could only insert coins and quit RetroArch... I'm afraid I don't have anything to add perhaps the fact this service/menu screen flashes yellow/blue could help. 

I'm using ROM for this very FBA version and I push no button whatsoever to enter this service screen.

**Comment by nemo93** [comment]
Same behavior on Mame 0.78 (libretro mame 2003 core) yet I could pass through this service menu screen after few seconds. With FBA the screen remains forever...

**Comment by thomasgoldstein** [comment]
I managed to play this game. You can pass that screen if you wait 30 seconds, no need to press anything.

**Comment by nemo93** [comment]
My bad! you're absolutely right thanks for having a look and being more patient :D
