### ISSUE TITLE
crash in set_environment() due to out of range assignment

### ISSUE THREAD

**Issue by yurivict** [libretro/libretro-fba#48]
struct retro_variable vars[nbr_vars + nbr_dips] is allocated with 3 elements, and then an element [3] is assigned, resulting in crash.

idx_var=3 nbr_vars=3 nbr_dips=0

**Comment by fr500** [comment]
hmmm with any particular game? it's working fine here

**Comment by yurivict** [comment]
I just built on FreeBSD, never ran any games, supplies random file as a game. It shouldn't access unallocated element.

Where does one get games for libretro-fba?

**Comment by fr500** [comment]
can't discuss that here

**Comment by yurivict** [comment]
Anyway, just fix the memory access.

**Comment by barbudreadmon** [comment]
imho it's a memory access crash because you load crap, not sure how to fix it without breaking anything ( that's part of the latest commits from @AkimanBengus ), perhaps he'll take a look.

**Comment by yurivict** [comment]
No, this happens with legitimate games too. I had to add +1 to the size of that array. I use clang compiler, maybe that's why it came up.

**Comment by barbudreadmon** [comment]
You mean changing "struct retro_variable vars[nbr_vars + nbr_dips]" to "struct retro_variable vars[nbr_vars + nbr_dips + 1]" fixed it ?

**Comment by yurivict** [comment]
yes

**Comment by AkimanBengus** [comment]
I just wake up now and I see this issue.
Sorry I forgot to allocate space for the last empty retro_variable :-(
And +1 is really what I had to do.
Thanks for the fix.

**Comment by yurivict** [comment]
You welcome!

**Comment by AkimanBengus** [comment]
Is it possible to fix the v0.2.97.36 release with this fix for people who wants to download it?

**Comment by barbudreadmon** [comment]
Done
