### ISSUE TITLE
No release for v0.2.97.37?

### ISSUE THREAD

**Issue by yurivict** [libretro/libretro-fba#49]
Your commit says Upgrade to v0.2.97.37, but release is for v0.2.97.36, made the same day.

**Comment by fr500** [comment]
it's the last version before it got updated, every revision from now on is .37

**Comment by yurivict** [comment]
But https://github.com/libretro/libretro-fba/releases doesn't have v0.2.97.37

**Comment by fr500** [comment]
he seems to be tagging on the last release, all the libretro related improvements till next version will be .37, I guess it will be tagged when there is a .38

**Comment by barbudreadmon** [comment]
exactly as @fr500 said, v0.2.97.37 release will be the final revision of libretro-fba before i commit v0.2.97.38.
