### ISSUE TITLE
Shared library doesn't reflect profile

### ISSUE THREAD

**Issue by yurivict** [libretro/libretro-fba#50]
makefile.libretro says it can understand accuracy, balanced and performance as profiles, but shared lib isn't named as such. Another core, bsnes, does create separate shared libraries.

Shouldn't fba do the same as bsnes ?

**Comment by barbudreadmon** [comment]
the profile thing is more of a hack i introduced for low hardware, and only profile=performance do something different from stand-alone fba at the moment (a speedhack on sh2 cpu and some irem drivers). Perhaps using a profile={accuracy,balanced,performance} scheme was not the best practice, but I don't intend on having 3 cores with different name for 4-5 speedhacks, that would be totally overkill.

**Comment by yurivict** [comment]
ok, thanks
