### ISSUE TITLE
Sound issues on Raspberry Pi 2 with NeoGeo games

### ISSUE THREAD

**Issue by objectchris** [libretro/libretro-fba#51]
I've been running this core for neogeo games and it seems to have sound issues - the sound is skipping constantly (it might be the core dropping frames, although the gameplay seems stable). It happens very noticeably in the start-up jingle, and in games with 'synthy' type music (eg neo turf masters).

Normally I'd put this down to the weak Pi 2, but it runs neogeo games just fine on another FBA core (https://github.com/libretro/fba-libretro) - I'd just use that but it doesn't have the core input remapping and dip switch which is so awesome!

I have the latest update. I thought I'd run neogeo games on this core before the .37 update, and they worked fine, but I can't be sure!

**Comment by objectchris** [comment]
Sorry, meant to attach my config in case it's a setup issue? 
[retroarch.cfg.txt](https://github.com/libretro/libretro-fba/files/33474/retroarch.cfg.txt)

**Comment by barbudreadmon** [comment]
Could you attach your /boot/config.txt ?

I confirm it's a setup issue since i can't reproduce it on my raspberry pi, but i can't confirm if it's your distro (i stopped using retropie a year ago because of speed issues) or your settings.

**Comment by objectchris** [comment]
no problem! attached:
[config.txt](https://github.com/libretro/libretro-fba/files/35045/config.txt)

**Comment by barbudreadmon** [comment]
i use those settings for overclock :

arm_freq=1100
sdram_freq=500
core_freq=500
over_voltage=6
gpu_mem=384

Could you check if you still have sound issues with those settings ?

**Comment by objectchris** [comment]
unfortunately that's not a stable overclock for me, although I did get the game running (but with same audio problems). I also get the problem with fba-libretro now! so it's clearly not a problem with this core. I tried installing the latest, and then the older binary of retroarch, but neither made a difference. I think I will re-install retropie and start from scratch - thanks!

**Comment by barbudreadmon** [comment]
Retropie is rpi2-compatible but not rpi2-optimized, perhaps you should give a try to recalbox which is rpi2-optimized.

**Comment by objectchris** [comment]
I did a complete re-install of retropie and it's working fine now! not sure what exactly caused the issue - possibly rebuilding retroarch to the latest versions. I might take a backup of my card and experiment...
