### ISSUE TITLE
cannot "make" lib on raspberry pi 2 with command given in README

### ISSUE THREAD

**Issue by bbourqu** [libretro/libretro-fba#53]
pi@raspberrypi ~/libretro-fba $ sudo make -f makefile.libretro platform=rpi2 profile=performance
LD fba_libretro.so
src/burn/burn.o:(.data.rel.ro+0x19d8): undefined reference to `BurnDrvDoDonpachijH'
src/burn/burn.o:(.data.rel.ro+0x226c): undefined reference to `BurnDrvCpsFfightbl2'
src/burn/burn.o:(.data.rel.ro+0x3174): undefined reference to `BurnDrvketarr17'
src/burn/burn.o:(.data.rel.ro+0x3178): undefined reference to `BurnDrvketstoicu'
src/burn/burn.o:(.data.rel.ro+0x3184): undefined reference to `BurnDrvKetalt'
src/burn/burn.o:(.data.rel.ro+0x3488): undefined reference to `BurnDrvLedstrm2'
src/burn/burn.o:(.data.rel.ro+0x52e4): undefined reference to `BurnDrvroute16b'
src/burn/burn.o:(.data.rel.ro+0x6e70): undefined reference to `BurnDrvkof98co'
src/burn/burn.o:(.data.rel.ro+0x7774): undefined reference to `BurnDrvVigilantj'
src/burn/burn.o:(.data.rel.ro+0x7778): undefined reference to `BurnDrvVigilantu'
src/burn/burn.o:(.data.rel.ro+0x777c): undefined reference to `BurnDrvVigilantu2'
src/burn/burn.o:(.data.rel.ro+0x7780): undefined reference to `BurnDrvVigilant1'
src/burn/burn.o:(.data.rel.ro+0x7ff4): undefined reference to `BurnDrvZigzag'
src/burn/burn.o:(.data.rel.ro+0x7ff8): undefined reference to `BurnDrvZigzag2'
collect2: error: ld returned 1 exit status
makefile.libretro:599: recipe for target 'fba_libretro.so' failed
make: *** [fba_libretro.so] Error 1

**Comment by barbudreadmon** [comment]
There is no kof98co in current fba set, neither a single reference to BurnDrvkof98co in sources, so you obviously did something wrong. My guess is that you updated sources inside a directory where there was already a compiled version of libretro-fba, and didn't clean before compiling again, so old code and new code are mixed : try running "sudo make -f makefile.libretro clean" prior to building, if it fails, delete your directory, clone again then build.

**Comment by bbourqu** [comment]
That did the trick @barbudreadmon thank you so much
