### ISSUE TITLE
[Feature request] Implement VMM for limited RAM environments

### ISSUE THREAD

**Issue by thatcadguy** [libretro/libretro-fba#54]
I use the FBA port on the Wii, which for RAM reasons can't load larger than about a 20 MiB ROM. I went to the FBA forums to ask how they've handled it and they said on the Xbox1, some FBA ports have used something called a VMM (I'm assuming that stands for virtual memory manager) in order to open larger ROMs. I think with a fast SD card, this would be worth looking into. Basically the idea is to only load what is immediately needed into RAM and store the rest in a pagefile on the SD card. I think this should be possible for games like Metal Slug X, 3, 4, 5 where the game is split up into several missions, i.e. only need to load what is needed for 1 mission at a time.

Reference: http://neosource.1emulation.com/forums/index.php?topic=2832.0
Couldn't find much more on it.

**Comment by barbudreadmon** [comment]
I'm not 100% sure but i think what you are asking is a retroarch feature, not a libretro core feature. Perhaps @twinaphex or any other retroarch dev could clarify this.

**Comment by Alcaro** [comment]
Doesn't sound like a front feature to me, need_fullpath should be sufficient.

Or if it's not sufficient, it would require changing both (though libretro extensions like that generally go under RetroArch).
