### ISSUE TITLE
Saving EEPROM not working on CPS2

### ISSUE THREAD

**Issue by fr500** [libretro/libretro-fba#56]
I'm pretty sure I fixed this but now I can't figure out why it doesn't save anymore...
Or maybe I didn't for this particular case?

Can anyone confirm?

**Comment by barbudreadmon** [comment]
Can i close ?

**Comment by AkimanBengus** [comment]
Yes it can be closed, this is fixed since the 13 Feb on v0.2.97.37.
I also checked the new version v0.2.97.38 and the fix is still there :-)
