### ISSUE TITLE
Issue starting rom, Night Warriors: Darkstalkers' Revenge

### ISSUE THREAD

**Issue by orbea** [libretro/libretro-fba#71]
I acquired roms from two different sources for the cp2 game `Night Warriors: Darkstalkers' Revenge`, but individually they do not work. No error messages, RetroArch just immediately quits. However I am not sure they are corrupted because if I have both zip files in my roms directory at once one of them starts to work...

The two roms:
```
$ du -h nwarr*.zip
20M	    nwarr.zip
2.2M	nwarru.zip

$ md5sum nwarr*.zip
8581fd3e0a87da7abbf198b3c2d20e9d  nwarr.zip
54c6aa919cd20832dc1e980222a8a414  nwarru.zip
```
```
nwarr$ md5sum *
fbfb6bd28ad4d4f9ccd63cadfef21890  readme.html
998a35b225c7636cbf91ac3715720ddd  vph.01
686b25629ab895ea8413ff1aac8a1686  vph.02
79a682c23dcf5f8241703b038b50eeae  vph.11
6ce6c69a04a318a6159f12a271bb5b2e  vph.12
bf3d41d75b822d0bbace58b8af2c480d  vph.13
e69b8a75f185cae2fc02475e48ca238b  vph.14
d4524c370d9e798d5dc158e5eee7235f  vph.15
42d2a0fc6696f4e28f438ab24d1187c0  vph.16
26118ea6932c69092439f06fed75f279  vph.17
c3ba0c8eb4621cc1ffc74429deb9147b  vph.18
57417a44f00932814e19c3333df8aa27  vph.19
eabb3be2188365f75ee7774416e8b4f9  vph.20
9f501b496b5a23b15920504ff4a33680  vphu.03f
442734706aed110c4313d102f57b657f  vphu.04c
d1870b0d642bc9cf2ab80e5c952b1641  vphu.05e
d6d6b9b8b965aa353fffcc6fcd569f41  vphu.06c
ca4c77ea74f1b1a1d30d614c18f8ea12  vphu.07b
0c908d0274872ec2dca5dc0e44516151  vphu.08b
cbff5a11fe645c342f5ad114b7f3f6da  vphu.09b
1276e6023555bd02aa08f93edb5bce89  vphu.10b
c38a9e4ba19d1b94a93572743e519309  vphux.03f
ff0e29f6fc93df0b851f95e421731399  vphux.04c
2814ea022b335d8f1224184c56de595e  vphux.05e
```
```
nwarru$ md5sum *
9f501b496b5a23b15920504ff4a33680  vphu.03f
442734706aed110c4313d102f57b657f  vphu.04c
d1870b0d642bc9cf2ab80e5c952b1641  vphu.05e
d6d6b9b8b965aa353fffcc6fcd569f41  vphu.06c
ca4c77ea74f1b1a1d30d614c18f8ea12  vphu.07b
0c908d0274872ec2dca5dc0e44516151  vphu.08b
cbff5a11fe645c342f5ad114b7f3f6da  vphu.09b
1276e6023555bd02aa08f93edb5bce89  vphu.10b
c38a9e4ba19d1b94a93572743e519309  vphux.03f
ff0e29f6fc93df0b851f95e421731399  vphux.04c
2814ea022b335d8f1224184c56de595e  vphux.05e
```
If both zip files are in the same directory `nwarru.zip` starts to work. If I combine both roms into a single new zip file with all of the files, it still does not work. Any ideas why this is happening?

**Comment by barbudreadmon** [comment]
There are dat files in repository, use clrmamepro.

**Comment by orbea** [comment]
That is not a very practical solution on GNU/Linux and it doesn't work either...

**Comment by dankcushions** [comment]
there are WINE versions of clrmamepro if you look. either way, this is just how fba/mame works. you need the parent unless you rebuild your romset using clrmamepro.

**Comment by hizzlekizzle** [comment]
The long answer is that your parent ROM seems to be from the wrong ROMset, while your child ROM is from the correct set. Normally, you could run the parent on its own but in this case it needs the files from the child ROM to supersede the non-correct bits.

If you're wanting to run the *u ROM, congratulations, you're all set. It would have needed a working parent ROM anyway. If you're wanting to run the parent ROM alone, you'll need to find one from the correct ROMset. MD5 of 39791a01599ff48f7d5ec3e5e4a08855 seems to work for me.

**Comment by barbudreadmon** [comment]
As i said, use clrmamepro, it works fine on linux, i use it. i added dat files to the repository so i would stop seeing people reporting issues about libretro-fba when they just have the wrong romset.

**Comment by orbea** [comment]
clrmamepro starts in wine, but none of the fixes work, In fact it leaves the rom sets even more broken.
Anyways, its not at all cool for the solution to be a proprietary program that only works in wine...

@hizzlekizzle thanks for the explanation, that was quite informative.

**Comment by barbudreadmon** [comment]
You are wrong, clrmamepro didn't break your rom set, your rom set was broken from the very start, resulting in your issue. clrmamepro removed the files that didn't belong in a valid rom set. Now you need to find the valid ones. There are websites providing full fba 0.2.97.38 romsets, they are easily googlable.

About clrmamepro, it is REALLY COOL of the developpers to develop a freeware with linux compatibility through wine in mind, there is even tips on how to solve some graphical glitches on their homepage.
