### ISSUE TITLE
Failed to build on Linux ARMhf

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/libretro-fba#74]
It was building fine until 8821a6c.

```
/bin/sh: 1: arm-linux-androideabi-gcc: not found
```

https://launchpadlibrarian.net/259889710/buildlog_ubuntu-vivid-armhf.libretro-fba_0.2.97.38+r90+n47+co28+ct45~16~ubuntu15.04.1_BUILDING.txt.gz

@diablodiab

**Comment by diablodiab** [comment]
It's probably because I changed these lines when I was cross-compiling it:
https://github.com/libretro/libretro-fba/blob/master/makefile.libretro#L220-L221

You could try reverting those lines back to:
https://github.com/libretro/libretro-fba/blob/b55216c1582313bb770a7d8d2032acd384537387/makefile.libretro#L219-L220

**Comment by sergiobenrocha2** [comment]
Eh, you really shouldn't change those lines... include a ifeq if you really need that.

**Comment by sergiobenrocha2** [comment]
```
PLATFORM_DEFINES += -DANDROID -Dlog2\(x\)=\(log\(x\)/1.4426950408889634\)
```
This too must be inside an ifeq

**Comment by sergiobenrocha2** [comment]
```
else ifneq (,$(findstring armv,$(platform)))
	TARGET := $(TARGET_NAME)_libretro.so
	TARGET := fb_alpha_libretro_android.so
```

This is wrong too for ARM linux distro context

**Comment by diablodiab** [comment]
It was just a quick hack I did in my own fork and was not meant to be pulled directly into the main repo.

**Comment by fr500** [comment]
if it wasn't included there wouldn't be progress, now we can take a look
and fix it, no big deal let's just fix it.

**Comment by barbudreadmon** [comment]
Why the change from PAGE_* to PAGE_*1 in m6805_intf.cpp ? If the name is really the issue, it should be an issue in konami_intf.cpp and many others. Konami games are working on your nvidia shield ?

**Comment by barbudreadmon** [comment]
Did you try different toolchains in android ndk before modifying sources ?

**Comment by diablodiab** [comment]
I tried two different toolchains before changes the source. I was only getting compiler errors in m6805_intf.cpp. It was causing warnings about redefinitions in the other places, check for example the warnings about PAGE_SIZE in #/21

I'll try some Konami games when I get home and see if they are working.

I haven't spent time analyzing the difference between the usage in m6805_intf.cpp compared to the other places. In the hack I made in my repo I was just trying to get it to compile - now the fixing can begin.

**Comment by barbudreadmon** [comment]
@diablodiab : I rollbacked and rewrote things properly (prefixed all PAGE variables properly, merged apple/android defines about fopen64/ftello64/fseeko64 and changed a few things in makefile.libretro), everything should be ok now if you use something like "armv-android-whatever" as your platform variable, and everything should be back to normal for linux armhf users.

**Comment by diablodiab** [comment]
excellent, i'll have a look at how it compiles

**Comment by diablodiab** [comment]
I've only tested compiling the android-version using my toolchain, and it compiles fine and without warnings because you renamed the PAGE variables. I'm looking into making a JNI for building the Android version.

**Comment by sergiobenrocha2** [comment]
It's building again, thanks!

**Comment by marcushg85** [comment]
Hello. I'm new in github and I'd like to know how to build a core for armhf device  (nes classic mini ed). 
Is there something I can use as a guide? I'm really interested in some drivers that the last fbalpha  has (in i8051 driver) can I compile this libretro fbalpha for armhf but with the new drivers from the .40 version?
Thank you all!
