### ISSUE TITLE
Merged romset

### ISSUE THREAD

**Issue by lollo78** [libretro/libretro-fba#78]
Hi, 
the actual fba-libretro core can manage merged romset (with clone merged to the parents)?
If yes, how can I load a clone inside a merged romset?

**Comment by dankcushions** [comment]
This is an issue tracker for bugs... this isn't a bug :) Please close and ask on the forums and I will assist you there. http://www.libretro.com/forums/

**Comment by lollo78** [comment]
Done
http://libretro.com/forums/showthread.php?t=6006&p=40543#post40543
Thanks and sorry
