### ISSUE TITLE
Raspberry pi 2 

### ISSUE THREAD

**Issue by expandables2** [libretro/libretro-fba#8]
Error building on raspberry pi 2 i get this 
src/burn/drv/pst90s/d_1945kiii.cpp: In function 'INT32 DrvFrame()':
src/burn/drv/pst90s/d_1945kiii.cpp:420:1: internal compiler error: in push_minip                                                                                        ool_fix, at config/arm/arm.c:13055
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.7/README.Bugs> for instructions.
Preprocessed source stored into /tmp/cct5qC3P.out file, please attach this to yo                                                                                        ur bugreport.
makefile.libretro:574: recipe for target 'src/burn/drv/pst90s/d_1945kiii.o' fail                                                                                        ed
make: *** [src/burn/drv/pst90s/d_1945kiii.o] Error 1

**Comment by barbudreadmon** [comment]
I didn't try building with gcc-4.7, use gcc-4.8 or 4.9

**Comment by barbudreadmon** [comment]
Seems to be unrelated to gcc-4.7 but probably a bug in some versions of gcc ( https://gcc.gnu.org/bugzilla/show_bug.cgi?id=49423 ). Try with a different gcc, mine is gcc-4.8.2, it also build with gcc-4.9.3.

**Comment by barbudreadmon** [comment]
Closing, ICE are system issues, not emulator issues.
